### ISSUE TITLE
Why is there no folder with serial number 5?

### ISSUE THREAD

**Issue by sunupdong** [matschik/component-party#124]
* I'm curious, why is there no folder with sequence number 5? 😊
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/52030677/200180551-5093a452-75f2-4821-b4c6-f55a5f37db69.png">

**Comment by matschik** [comment]
I don't know how to count haha !
No, I think there was indeed 7 sections and I removed the 5th because it was not needed.
