### ISSUE TITLE
bug: props example with Angular

### ISSUE THREAD

**Issue by lauthieb** [matschik/component-party#32]
Hello, 
I think there is a problem with the "Props" example with Angular, it seems we don't have any props that we use in markup declared inside the component (but on React, Svelte & Vue it's ok).

- https://github.com/matschik/component-party/blob/main/content/4-component-composition/1-props/angular/app.component.ts
- https://component-party.pages.dev/#props

Thanks! :)

**Comment by matschik** [comment]
Some files were not displayed since a file name sorter was implemented.
I removed the file sorter temporarily to find a better solution #33 
Thank you for your report ! :)

**Comment by lauthieb** [comment]
@matschik perfect, thanks :)
