### ISSUE TITLE
Angular: Conditional alternative

### ISSUE THREAD

**Issue by nartc** [matschik/component-party#37]
Hi, thanks for this great site. 

I want to propose an alternative to the Conditional section for Angular. In addition to `*ngIf`, Angular also has `*ngSwitch` which fits the use-case in this section better

```html
<button (click)="nextLight()">Next light</button>
<p>Light is: {{ lightIndex | light }}</p>
<p>
    You must
    <ng-container [ngSwitch]="lightIndex | light">
        <span *ngSwitchCase="'red'">STOP</span>
        <span *ngSwitchCase="'orange'">SLOW DOWN</span>
        <span *ngSwitchCase="'green'">GO</span>
    </ng-container>
</p>
```

This way you don't have 3 instances for `TrafficLightPipe` instantiated for each `ngIf`

**Comment by matschik** [comment]
`Templating > Conditional` is meant to show how to do a single `if` and multiple `if`.
In this case a `Switch` is a better fit, yes.
The best way to answer this use-case is to create `Templating > Switch` #38
