### ISSUE TITLE
7GUIs tasks as examples (?)

### ISSUE THREAD

**Issue by SarcevicAntonio** [matschik/component-party#68]
7GUIs is a GUI programming benchmark, with interesting tasks that require usage of different GUI programming techniques.

I already have [a repo](https://github.com/SarcevicAntonio/as-guis) setup with the first few tasks done with Angular, React, Vue and Svelte.

If you also agree that these tasks provide good component examples, I can set up a PR.
It could either be it's own section, and / or replace (some) examples.

I could also just fork this project for my use, if you don't want these examples. We can also look at other benchmarks like TodoMVC, HackerNewsPWA, Rosetta Code, Flux Challenge, ThreaditJS and RealWorld App.

**Comment by matschik** [comment]
It would add too much work to maintain Component Party.
I want to keep it simple to focus on the most important parts.
Thanks for your suggestion !
