### ISSUE TITLE
React examples should always import `React`

### ISSUE THREAD

**Issue by Tropix126** [matschik/component-party#72]
To render JSX in React, it is required to import the base `React` module to run the transpiled `React.createElement()` calls. Many examples seem to only import `useState` or import nothing at all, which will throw a `ReferenceError` in practice.

![image](https://user-images.githubusercontent.com/42101043/168661133-548d83d1-0398-4fc8-8e76-41902846884f.png)
![image](https://user-images.githubusercontent.com/42101043/168661163-dbd02532-de1b-434e-a730-ca136746f29c.png)

Correct usage:
![image](https://user-images.githubusercontent.com/42101043/168661203-798055c4-1e13-47db-ae7a-93401463e9d8.png)

**Comment by matschik** [comment]
Fixed in #73

**Comment by matschik** [comment]
@LouisJS  Why is it a mistake ? Can you give some arguments ?

We got two arguments here:
- As @Tropix126  mentionned, using JSX implies the use of `React.createElement` to make it work for React renderer.
- By default, the eslint react plugin is throwing an error if `React` is not imported. Please read this for more informations: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md

Giving a link to StackOverflow is not enough.
