### ISSUE TITLE
You can use JSX without importing React

### ISSUE THREAD

**Issue by LouisJS** [matschik/component-party#76]
Since the new JSX transform (https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)
You can use JSX without importing React.

Importing React is only necessary when using React concept such as `useState` , `useEffect`, ect.

You should update your ESLint rules in order to allow this new good practice
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint

you can also use a script to perform the change
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports

FYI: The ReferenceError you could face is not on the React side, but on your configuration side
https://stackoverflow.com/questions/64072766/react-js-reference-error-react-is-not-defined

**Comment by matschik** [comment]
Changes from #72 have now be reverted. 
Thank you for your explanations to make Component Party better 🎉
