### ISSUE TITLE
Add native Web Component

### ISSUE THREAD

**Issue by meduzen** [matschik/component-party#92]
Would it make sense to add snippets for native Web Components? Maybe not for all categories but I guess a number of them could fit.

**Comment by matschik** [comment]
Can you provide an example for "declare state" and "update state" to see how it would looks ?

**Comment by meduzen** [comment]
I just started learning Web Components. I’ll come back on this issue if I think it’s worth it.

The reactivity part (declare, update and compute state) might be out of scope for Web Components, but the other 5 categories of the website are probably very relevant. 🤔
